#!/bin/sh

##
# Runit run script for openvpn
#

# Create TUN dev
mkdir /dev/net
mknod /dev/net/tun c 10 200

# Configure forwarding
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s 10.8.0.0/8 -o eth0 -j MASQUERADE

# Start openvpn service
exec /usr/sbin/openvpn --cd /etc/openvpn --config /etc/openvpn/server.conf

